export interface ConstructionPermit {
  id?: any,
  investor_id?: any,
  plan_submission_type_id?: any,

  professional_body_id?: any,
  membership_number?: any,
  consultant_name?: any,
  address?: any,
  email?: any,
  citizenship?: any,

  project_brief?: any,
  project_purpose?: any,

  parcel_id?: any,
  parcel_number?: any,
  latitute?: any,
  longitude?: any,
  min_density?: any,
  max_density?: any,
  size?: any,
  min_floor_area?: any,
  max_floor_area?: any,
  min_far?: any,
  max_far?: any,
  minimum_setback?: any,
  min_floor_to_floor_height?: any,
  max_floor_to_floor_height?: any,
  min_number_of_floors?: any,
  max_number_of_floors?: any,
  percentage_of_site_covered_by_existing_building?: any,
  percentage_of_site_covered_by_proposed_building?: any,
  number_of_units_to_be_developed?: any,
  planned_land_use_id?: any,
  primary_secondary_and_preferred_ground_floor_use?: any,

  site_plan_and_analysis?: any,
  context_analysis?: any,
  concept_plan?: any,
  geotechnical_report?: any,
  topographical_survey?: any,
  parking_strategy?: any,
  traffic_management_plan?: any,
  estimated_utility_demand_requirements?: any,

  project_sustainability_brief?: any,
  green_certification_id?: any,
  other_green_certification?: any,
  sustainability_report?: any,

  require_variations?: any,
  estimated_project_duration?: any,
  estimated_project_construction_cost?: any,
  commitment_to_comply_with_development_codes_and_guidelines?: any,


  status_id?: any,

  status?: any,
  investor?: any,
}
